version: '3.8'

services:
  app:
    build: .
    environment:
      - DEBUG=true
      - BOT_SLUG=knurl-jay-uv
      - SDK_API_TOKEN=DfNqHukqoUWSDQQfCyj3txbViwDiAbRG1cqbLM9h6hX6eB3JcjYiD9jBuWuhWMCDLB2hbnBsQL81xxg58oUvc9b1L28cnJrVcN3o
      - CHROME_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "8000:8000"
      - "9222:9222"
    volumes:
      - ./data:/app/data
